group_action: delete # ( create, delete, modify, add-member, remove-member)

create_group_names: 
  - devops
  - dev

modify_group_old_name: devops
modify_group_new_name: gitops

delete_groupe_name: testgitops
delete_refactor_group_name: dev

add_member_group_name: dev
add_member_member_name: ahmed

remove_member_group_name: dev
remove_member_member_name: ahmed