create_group_names: 
  - devops
  - dev

modify_group_old_name: devops
modify_group_new_name: gitops

delete_groupe_name: gitops
delete_refactor_group_name: dev

add_member_group_name: dev
add_member_member_name: amine

remove_member_group_name: dev
remove_member_member_name: amine